### ISSUE TITLE
API rate limits

### ISSUE THREAD

**Issue by ByteHamster** [Podcastindex-org/docs-api#16]
In #11, daveajones mentioned that the purpose of the API keys is to block keys that are "hammering the API". Do you have a rough estimate what you mean with that? Are 10k requests per day considered okay? What about 100k requests (for things like live suggestions while typing the search term)?

**Comment by daveajones** [comment]
I’m sorry this hasn’t been documented anywhere yet. I’ve been frying some bigger fish and there are a few things I haven’t gotten down yet in the docs.

You want to keep your requests at less than one per second in the case of sustained traffic. Search as you type is OK as long as you debounce it so that it’s not going over that rate.  We will hopefully have our TOS finalized and up soon.
