### ISSUE TITLE
new endpoint: recent/modifiedfeeds

### ISSUE THREAD

**Issue by filterdo** [Podcastindex-org/docs-api#87]
Is there currently a way to see which feeds have been updated since a certain date?  I can't tell if this is what recent/feeds accomplishes, since it maxes out at 1000 and there is no way to paginate beyond that.

**Comment by stevencrader** [comment]
That is what that endpoint is for but as you said, it has limitations. 

You can also access feeds from object storage at https://tracking.podcastindex.org/current or using the yet to be documented https://api.podcastindex.org/api/1.0/recent/data?pretty. To view prior blocks, pass the nextSince value https://api.podcastindex.org/api/1.0/recent/data?pretty&since=1671079551

I'll get this documented soon. I somehow missed it and just found it searching the social.

**Comment by filterdo** [comment]
Thanks @stevencrader - So to have the most current data, you loop through nextSince until you reach the date that you last retrieved updates from the API? Is that correct?

**Comment by stevencrader** [comment]
I believe that's how it's supposed to work

**Comment by daveajones** [comment]
If using the "tracking" url, just walk backwards through previousTrackingUrl's until you hit the last "position" you had.  That catches you up.

**Comment by filterdo** [comment]
I get an error:
"invalid json response body at https://tracking.podcastindex.org/current reason: Unexpected token < in JSON at position 0"

Any idea why?

**Comment by daveajones** [comment]
Working fine on my side.  What software or call type is giving you that error?

**Comment by filterdo** [comment]
Using node-fetch, but https://api.podcastindex.org/api/1.0/recent/data (and all other endpoints) works fine. So I am using that.
